### ISSUE TITLE
DOPLER Case Studies

### ISSUE THREAD

**Issue by RickRabiser** [but4reuse/espla_catalog#1]
Hi guys,

Great work on creating this catalog. You might want to have a look at our paper "D. Dhungana, P. Grünbacher, and R. Rabiser, The DOPLER Meta-Tool for Decision-Oriented Variability Modeling: A Multiple Case Study, Automated Software Engineering, vol. 18(1), pp. 77-114, 2011." (https://doi.org/10.1007/s10515-010-0076-6). 

It describes four case studies on SPL adoption, one being the MSS Case Study (Siemens VAI MSS tool) you already have in your list but the other three currently being missing, i.e.,

Case 1: Steel Plant Automation Software (CC-L2)
Case 2: IEC 61499 Industrial Automation Systems
Case 4: .NET Plug-in-based Business Software at BMD

For all these cases, there are also additional publications, but the ASE-J Paper nicely summarizes all information needed for your catalog :)

http://ase.jku.at/dopler is a homepage with further information and links to most DOPLER-related publications.

Unfortunately, the project has already finished in 2013, however, the catalog contains many cases, in which the project has already been finished, so I thought you still might want to add these cases.

Best,
Rick

**Comment by jabiercoding** [comment]
Thanks for your collaboration Rick. We will add these three case studies and eventually update some data for the existing one. Thanks for pointing to the correct reference.
By the way, as you may have noticed, the catalog has the DOPLER tool itself as another case study of SPL adoption. Feel free to check the data about the DOPLER tool and report new issues/fixes if found.
